// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbiK4NnjW6MwfxhR0P1aoDKQPbpfPD2zA',
    appId: '1:269625313801:web:4f9ee192240e221f0986d8',
    messagingSenderId: '269625313801',
    projectId: 'money-fb675',
    authDomain: 'money-fb675.firebaseapp.com',
    storageBucket: 'money-fb675.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgjsNNzfxOhTkliOiKG7d-PkpmiF8tyQE',
    appId: '1:269625313801:android:0ca9badccc5cb25b0986d8',
    messagingSenderId: '269625313801',
    projectId: 'money-fb675',
    storageBucket: 'money-fb675.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBLGzgrmY3i46XF_LDUiM4nrqEHoDc4gM',
    appId: '1:269625313801:ios:17655e52c8b3fb1f0986d8',
    messagingSenderId: '269625313801',
    projectId: 'money-fb675',
    storageBucket: 'money-fb675.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBLGzgrmY3i46XF_LDUiM4nrqEHoDc4gM',
    appId: '1:269625313801:ios:17655e52c8b3fb1f0986d8',
    messagingSenderId: '269625313801',
    projectId: 'money-fb675',
    storageBucket: 'money-fb675.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbiK4NnjW6MwfxhR0P1aoDKQPbpfPD2zA',
    appId: '1:269625313801:web:cb61d36c458234b20986d8',
    messagingSenderId: '269625313801',
    projectId: 'money-fb675',
    authDomain: 'money-fb675.firebaseapp.com',
    storageBucket: 'money-fb675.firebasestorage.app',
  );
}
